name: ledger_design_system
description: "Ledger Design System for ATOA"
version: 0.0.1
publish_to: none
homepage: https://github.com/ATOAPaymentsLimited/atoa-flutter-packages/tree/main/packages/ledger_design_system
repository: https://github.com/ATOAPaymentsLimited/atoa-flutter-packages/tree/main/packages/ledger_design_system
issue_tracker: https://github.com/ATOAPaymentsLimited/atoa-flutter-packages/issues

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_state_notifier: ^1.0.0
  shared_preferences: ^2.3.5
  flutter_screenutil: ^5.8.4
  meta: ^1.13.0
  provider: ^6.0.5
  bot_toast: ^4.0.4
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.2
  timelines: ^0.1.0
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  flutter_gen: ^5.0.0

flutter_gen:
  output: lib/assets/
  integrations:
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/fonts/
  fonts:
    - family: FigTree
      fonts:
        - asset: assets/fonts/FigTree/Figtree-VariableFont_wght.ttf
          style: normal
        - asset: assets/fonts/FigTree/Figtree-Italic-VariableFont_wght.ttf
          style: italic