name: face_detector_view
description: Face Detector View for KYB face liveness check
version: 1.0.7

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=3.19.5"

dependencies:
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  flutter_screenutil: ^5.5.4
  google_mlkit_face_detection: ^0.11.0
  image: ^4.0.17
  permission_handler: ^11.3.1
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
