name: regal
description: ATOA Design System which is used in all the Flutter Atoa products. It makes the theming and tracking events easy.

version: 3.8.0

homepage: https://github.com/ATOAPaymentsLimited/atoa-flutter-packages/tree/main/packages/regal
repository: https://github.com/ATOAPaymentsLimited/atoa-flutter-packages/tree/main/packages/regal
issue_tracker: https://github.com/ATOAPaymentsLimited/atoa-flutter-packages/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  auto_size_text: ^3.0.0
  bot_toast: ^4.1.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_state_notifier: ^1.0.0
  flutter_svg: ^2.0.7
  intl: ^0.19.0
  lottie: ^3.2.0
  meta: ^1.9.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  timelines: ^0.1.0
  vector_graphics: ^1.1.18

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: false
    lottie: true

flutter:
  generate: true
  assets:
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
    - family: FigTree
      fonts:
        - asset: assets/fonts/FigTree/Figtree-VariableFont_wght.ttf
        - asset: assets/fonts/FigTree/Figtree-Italic-VariableFont_wght.ttf
          style: italic
